### PR TITLE
Rversion

### PR DESCRIPTION
**Pull request by joethorley**
Set R version to 3.4 and test in travis

### CODE REVIEW

**Comment by ateucher** [comment]
Why do we need to set the minimum R version? If rems truly requires R 3.5 (I honestly can't remember why!) then it will enforce that requirement, but are there features in wqbc that need a minimum version of 3.4 or 3.5?

**Comment by joethorley** [comment]
The initial message is confusing - I eventually set wqbc to 3.5 same as rems. I feel like its helpful for users to specify the minimum version required and to explicitly test it in travis.

**Comment by ateucher** [comment]
I agree about testing the minimum version, but since rems is just in Suggests (wqbc can work without it) I'd rather not force an unnecessarily high R version in this package. If it passes all checks and tests at R 3.4, let's set it at that.

**Comment by ateucher** [comment]
However it does make checking it on Travis more difficult...

**Comment by joethorley** [comment]
I don't know how to make Travis test a package without being sensitive to the R dependency version of a suggested package.
However, I just confirmed that rems works on R 3.4. I've submitted a pull request to rems to change from R >= 3.5 to R >= 3.4 and update this pull request to wqbc to use R >= 3.4 and the most recent version of rems.

**Comment by ateucher** [comment]
That is perfect - that was going to be my next thing to do. Thanks Joe!

**Pull request merged**
